In [ ]:
# this is a program to slice my mosue brain RNAseq results from David McGaughey's analysis of 
# Cd320KO mice on B12 deficient diet from Control mice on B12-deficient diet
# CSV file is "original_cd320.KOB12neg_vs_ctrlB12neg"
# path is dbernard/Documents/DJB files/Brody Lab/mouse CD320/Brain RNA seq experiment/Brain RNAseq analysis by McGaughey/

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("original_cd320.koB12neg_vs_ctrlB12neg_copy.csv")
df.head()

,Gene,Source,Chr,Start,End,baseMean,log2FoldChange,log2FoldChangeUncorrected,lfcSE,stat,...,Control.Normal.B12_10,Control.Normal.B12_15,KO.B12_Deficient.B12_03,KO.B12_Deficient.B12_04,KO.B12_Deficient.B12_06,KO.B12_Deficient.B12_07,KO.Normal.B12_01,KO.Normal.B12_08,KO.Normal.B12_11,KO.Normal.B12_12
0,Tmem181a,HAVANA,chr17,6270470,6308314,14902.552866,-0.686035,-0.712041,0.017077,-40.172218,...,18346.249782,18475.883409,11224.547655,11321.244681,11175.307230,11333.126407,11434.949103,11357.689735,11390.642607,11424.623768
1,Cd320,HAVANA,chr17,33843091,33849774,176.246376,-1.195882,-6.074842,0.043120,-27.733483,...,300.828145,367.548311,1.964394,9.866868,2.164499,6.732741,4.370490,4.140986,7.076582,2.035386
2,Gm16867,HAVANA,chr14,69363504,69503362,1749.882377,-0.696872,-0.870387,0.036290,-19.202594,...,2202.872764,2258.910973,1294.535685,1178.104074,1206.708073,1251.327969,1364.466867,1271.282745,1241.055493,1282.293421
3,Entpd4,HAVANA,chr14,69337174,69367270,5582.269809,-0.492651,-0.551765,0.028132,-17.512058,...,6801.703024,6552.499203,4684.097634,4298.007829,4510.815469,4420.525245,4662.438352,4484.687990,4729.810206,4548.070873
4,Pyroxd2,ENSEMBL,chr19,42725858,42752775,210.092764,0.622038,1.512406,0.045080,13.798491,...,97.075749,102.367567,296.623503,301.926170,314.934573,304.896976,334.779507,303.327235,353.829078,309.378730

In [4]:
df.tail()

,Gene,Source,Chr,Start,End,baseMean,log2FoldChange,log2FoldChangeUncorrected,lfcSE,stat,...,Control.Normal.B12_10,Control.Normal.B12_15,KO.B12_Deficient.B12_03,KO.B12_Deficient.B12_04,KO.B12_Deficient.B12_06,KO.B12_Deficient.B12_07,KO.Normal.B12_01,KO.Normal.B12_08,KO.Normal.B12_11,KO.Normal.B12_12
19987,Vmn2r73,HAVANA,chr7,85857547,85875938,0.061520,0.0,0.0,0.001917,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0
19988,Wfdc21,HAVANA,chr11,83746940,83752642,0.109917,0.0,0.0,0.001917,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.874098,0.000000,0.884573,0.0
19989,Zdhhc25,HAVANA,chr15,88600302,88601669,0.054631,0.0,0.0,0.001917,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.874098,0.000000,0.000000,0.0
19990,Zfp352,HAVANA,chr4,90218820,90225702,0.064703,0.0,0.0,0.001917,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.035247,0.000000,0.0
19991,Zfp616,HAVANA,chr11,74069955,74087292,0.061520,0.0,0.0,0.001917,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0

In [3]:
#slice file to get only the columns for Gene, log2FoldChange and padj in newdf
newdf= df.loc[:,['Gene','log2FoldChange','padj']]
newdf.head()

#df = newdf
#df.head()

       Gene  log2FoldChange          padj
0  Tmem181a       -0.686035  2.966812e-13
1     Cd320       -1.195882  2.966812e-13
2   Gm16867       -0.696872  2.966812e-13
3    Entpd4       -0.492651  2.966812e-13
4   Pyroxd2        0.622038  2.966812e-13

In [8]:
#save sliced dataframe as .csv file
newdf.to_csv(r'/Users/dbernard/newdf.txt', sep = '\t', index = False)
#newdf.head()

In [7]:
import os
!cwd()

/bin/sh: -c: line 1: syntax error: unexpected end of file

In [7]:
file = open('test.csv','w')
file.write("newdf")

5

In [ ]:
# This newdf file can now be uploaded to P